### ISSUE TITLE
Добавить обработку деления на 0 в 5-й лабе

### ISSUE THREAD

**Issue by denis-bosiy** [pklgn/dotnet-practice-labs#1]
Сейчас падает ошибка :-(
![image](https://github.com/pklgn/dotnet-practice-labs/assets/48645130/ff2a63d9-6eff-4012-99de-6a5df57f54dc)

**Comment by denis-bosiy** [comment]
Не заметил, что деление не добавлено

**Comment by pklgn** [comment]
Пока обработку разного рода нештатных ситуаций решил сделать на уровне перенаправления на страницу с ошибкой
Для деления придумаю что-то другое, когда реализую операцию 👌
