### ISSUE TITLE
Незачем передавать callback

### ISSUE THREAD

**Issue by AkshachRd** [pklgn/dotnet-practice-labs#10]
https://github.com/pklgn/dotnet-practice-labs/blob/0aa8efd365831a549e9f0a8d61a40df5f039c498/lab7/src/components/Reviewer/Reviewer.tsx#L37-L39
Ты можешь передавать туда callback, но он нужен, чтобы из параметров получать текущее состояние.
В твоём случае, это лишь усложнение. Можешь просто устанавливать значение и будет то же самое.

**Comment by pklgn** [comment]
Убрал лишние callback'и
