### ISSUE TITLE
Решение со звёздочками

### ISSUE THREAD

**Issue by AkshachRd** [pklgn/dotnet-practice-labs#11]
https://github.com/pklgn/dotnet-practice-labs/blob/0aa8efd365831a549e9f0a8d61a40df5f039c498/lab7/src/components/Reviewer/StarGrade/StarGrade.tsx#L10-L51
Решение с dataset мне лично не очень нравится. У нас тут дз было про React и TS, а тут нативные JS методы. Но в целом норм.
На самом деле, тебе это только усложнило код. Также index в key это не очень хорошая практика, но тоже приемлемо.

**Comment by pklgn** [comment]
Убрал дублирование значения индекса в `data-index` и использую его теперь напрямую в обработчике `onMouseOver`
