### ISSUE TITLE
Задание стилей элементу

### ISSUE THREAD

**Issue by AkshachRd** [pklgn/dotnet-practice-labs#13]
https://github.com/pklgn/dotnet-practice-labs/blob/0aa8efd365831a549e9f0a8d61a40df5f039c498/lab7/src/components/Common/Textarea/Textarea.tsx#L14-L20
В реакте мы фундаментально стараемся как меньше взаимодействовать с DOM, потому что подобные действия разрывают наш флоу работы приложения, и из-за этого оно работает медленнее и менее понятно. Также это недекларативно.
В таком случае обычно выносят всё что тебе нужно в классы в css файл, создают состояние типа `isTextAreaHightlighted` и в `className` пришут ```className={`${isTextAreaHightlighted && "textArea_highlighted"}`}```
В данном же случае, тебе надо задавать высоту динамически. Ты можешь сделать состояние `textAreaHeight` типа number, менять его в `handleTextChange`, а в компоненте сделать переменную `textAreaStyles`, где и задавать стили, потом передавать это в пропсы.
Примерно так.
![image](https://github.com/pklgn/dotnet-practice-labs/assets/29169528/78540aca-e6c3-41a9-b0a6-40b8e17855d4)
![image](https://github.com/pklgn/dotnet-practice-labs/assets/29169528/c303daf4-1575-441e-91aa-b966408f3a45)
![image](https://github.com/pklgn/dotnet-practice-labs/assets/29169528/f97b27ad-816c-4f04-a721-0bf661b78d57)
![image](https://github.com/pklgn/dotnet-practice-labs/assets/29169528/17b532ca-2d2e-4e66-877a-d223857f4f9d)

**Comment by pklgn** [comment]
Спасибо за подробный пример. Попробовал сделать с помощью состояний, но столкнулся с проблемой: помимо установления значения `event.target.scrollHeight` нужно перед этим всегда "сбрасывать" значение высоты 
`textarea` (как например [здесь](https://stackoverflow.com/questions/39401504/javascript-react-dynamic-height-textarea-stop-at-a-max)). 
Поэтому вместо присвоения состоянию `textAreaHeight` значения `event.target.scrollHeight` сразу, я в обработчике события `textarea` `onChange` сначала сбрасываю высоту через `setTextAreaHeight(null)`, а уже потом, в `useLayoutEffect` я устанавливаю новое состояние через `textareaRef`.
Возможно, существует более элегантное решение проблемы
