### ISSUE TITLE
Не прописан foreign key

### ISSUE THREAD

**Issue by AlekseiPavlovskii** [pklgn/dotnet-practice-labs#14]
https://github.com/pklgn/dotnet-practice-labs/blob/0aa8efd365831a549e9f0a8d61a40df5f039c498/lab3/SpaceObjectsCreate.sql#L11

В полях внешних ключей нет команды создания внешнего ключа. Таблицы де-факто не связаны

**Comment by pklgn** [comment]
Поправил

**Comment by AlekseiPavlovskii** [comment]
Не нужно делать alter table, достаточно в create table прописать поле как ключ
[id_planet_type] int not null constraint FK_planet_planet_type references planet_type(id_planet_type)

**Comment by pklgn** [comment]
Переупорядочил создание таблиц, добавил создание внешнего ключа в момент создания таблицы
