### ISSUE TITLE
Nullable поля

### ISSUE THREAD

**Issue by AlekseiPavlovskii** [pklgn/dotnet-practice-labs#15]
https://github.com/pklgn/dotnet-practice-labs/blob/0aa8efd365831a549e9f0a8d61a40df5f039c498/lab3/SpaceObjectsCreate.sql#L11

Not null прописано только у первичных ключей, у остальных полей не указано. Необходимо определить, какие поля точно не могут быть null (например название планеты) и прописать им not null

**Comment by pklgn** [comment]
Добавил необходимые NOT NULL
