### ISSUE TITLE
Некорректный тип проекта

### ISSUE THREAD

**Issue by AlekseiPavlovskii** [pklgn/dotnet-practice-labs#18]
https://github.com/pklgn/dotnet-practice-labs/blob/0aa8efd365831a549e9f0a8d61a40df5f039c498/lab4/SpaceObjects/DatabaseProvider/DatabaseProvider.csproj#L4

DatabaseProvider должен быть библиотекой классов (а не запускаемым проектом). Это можно перенастроить в .csproj файле. Также нужно удалить точку входа (Program.cs)

**Comment by pklgn** [comment]
Поправил
