### ISSUE TITLE
Пропсы это не тип для использования

### ISSUE THREAD

**Issue by AkshachRd** [pklgn/dotnet-practice-labs#9]
https://github.com/pklgn/dotnet-practice-labs/blob/0aa8efd365831a549e9f0a8d61a40df5f039c498/lab7/src/components/Reviewer/Reviewer.tsx#L12
Привет!
Пропсы нужны для указания того, что ты передаешь в компонент. Ты не можешь их экспортировать и использовать как тип.
Зато ты можешь создать тип `Grade` и использовать его как пропсы `type GradeProps = Grade`!

**Comment by pklgn** [comment]
Поправил
